@startuml data_pipeline
title Data Pipeline
footer Disponível em: https://github.com/acnaweb/mackenzie

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_LANDSCAPE()

Person(user, "Usuário")

System_Boundary(transactional, "Transacional") {

        Container(frontend, "Frontend", "Angular", "Web App de interação")
        Container(api, "API", "Java", "")
        ContainerDb(db, "Database", "Oracle")
}


Rel(user, frontend, "Realizar pedidos")
Rel(frontend, api, "Consumir endpoints")
Rel(api, db, "Persistir dados")

@enduml